version: '3.8'

services:
  frontend:
    build:
      context: ./brainlook-frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - FAST_REFRESH=false
        - CHOKIDAR_USEPOLLING=true
    image: ewgao/brainlook:frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./brainlook-backend
      dockerfile: Dockerfile
    image: ewgao/brainlook:backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "8080:8080"
